name: release

on:
  workflow_run:
    workflows: ['ci']
    branches: [main]
    types: [completed]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        uses: bahmutov/npm-install@v1

      - name: Build
        if: ${{ steps.release.outputs.release_created }}
        run: yarn build

      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
